# Generated by Django 3.1.7 on 2021-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('RollNo', models.IntegerField()),
                ('Mark', models.FloatField()),
                ('Depart', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
