# Generated by Django 3.1.7 on 2021-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('RollNo', models.IntegerField()),
                ('Mark', models.FloatField()),
                ('Depart', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Depart',
            field=models.CharField(max_length=255),
        ),
    ]
